---
{
   "kind": "pipeline",
   "name": "publish_services",
   "steps": [
      {
         "commands": [
            "ls",
            "cd just_learn_Django",
            "docker-compose stop",
            "sudo git reset --hard",
            "sudo git pull",
            "sudo docker-compose build",
            "docker pull a26796879/just_learn_django",
            "docker pull a26796879/just_learn_celery",
            "docker-compose up -d"
         ],
         "image": "appleboy/drone-ssh",
         "name": "deploy-services",
         "settings": {
            "host": {
               "from_secret": "service_host"
            },
            "key": {
               "from_secret": "id_rsa"
            }
         },
         "when": {
            "event": {
               "exclude": [
                  "push"
               ]
            }
         }
      }
   ]
}
---
{
   "kind": "pipeline",
   "name": "publish_to_workers",
   "steps": [
      {
         "commands": [
            "ls",
            "cd just_learn_Django",
            "docker-compose stop",
            "sudo git reset --hard",
            "sudo git pull",
            "sudo docker-compose build",
            "docker pull a26796879/just_learn_django",
            "docker pull a26796879/just_learn_celery",
            "docker-compose up -d"
         ],
         "image": "appleboy/drone-ssh",
         "name": "deploy-workers",
         "settings": {
            "host": {
               "from_secret": "celery1_host"
            },
            "key": {
               "from_secret": "id_rsa"
            }
         },
         "when": {
            "event": {
               "exclude": [
                  "push"
               ]
            }
         }
      }
   ]
}
---
{
   "kind": "pipeline",
   "name": "publish_to_workers",
   "steps": [
      {
         "commands": [
            "ls",
            "cd just_learn_Django",
            "docker-compose stop",
            "sudo git reset --hard",
            "sudo git pull",
            "sudo docker-compose build",
            "docker pull a26796879/just_learn_django",
            "docker pull a26796879/just_learn_celery",
            "docker-compose up -d"
         ],
         "image": "appleboy/drone-ssh",
         "name": "deploy-workers",
         "settings": {
            "host": {
               "from_secret": "celery2_host"
            },
            "key": {
               "from_secret": "id_rsa"
            }
         },
         "when": {
            "event": {
               "exclude": [
                  "push"
               ]
            }
         }
      }
   ]
}
---
{
   "kind": "pipeline",
   "name": "publish_to_workers",
   "steps": [
      {
         "commands": [
            "ls",
            "cd just_learn_Django",
            "docker-compose stop",
            "sudo git reset --hard",
            "sudo git pull",
            "sudo docker-compose build",
            "docker pull a26796879/just_learn_django",
            "docker pull a26796879/just_learn_celery",
            "docker-compose up -d"
         ],
         "image": "appleboy/drone-ssh",
         "name": "deploy-workers",
         "settings": {
            "host": {
               "from_secret": "celery3_host"
            },
            "key": {
               "from_secret": "id_rsa"
            }
         },
         "when": {
            "event": {
               "exclude": [
                  "push"
               ]
            }
         }
      }
   ]
}
