---
{
   "kind": "pipeline",
   "name": "publish-services_just_learn_django",
   "steps": [
      {
         "auto_tag": true,
         "cache_from": "a26796879/just_learn_django:drone-build",
         "image": "plugins/docker",
         "name": "deploy-workers",
         "repo": "a26796879/just_learn_django",
         "settings": {
            "password": {
               "from_secret": "docker_password"
            },
            "username": {
               "from_secret": "docker_username"
            }
         },
         "when": {
            "event": {
               "exclude": [
                  "push"
               ]
            }
         }
      }
   ]
}
---
{
   "kind": "pipeline",
   "name": "publish-services_just_learn_celery",
   "steps": [
      {
         "auto_tag": true,
         "cache_from": "a26796879/just_learn_celery:drone-build",
         "image": "plugins/docker",
         "name": "deploy-workers",
         "repo": "a26796879/just_learn_celery",
         "settings": {
            "password": {
               "from_secret": "docker_password"
            },
            "username": {
               "from_secret": "docker_username"
            }
         },
         "when": {
            "event": {
               "exclude": [
                  "push"
               ]
            }
         }
      }
   ]
}
---
{
   "kind": "pipeline",
   "name": "publish_services",
   "steps": [
      {
         "commands": [
            "ls",
            "cd just_learn_Django",
            "docker-compose stop",
            "sudo git reset --hard",
            "sudo git pull",
            "sudo docker-compose build",
            "docker pull a26796879/just_learn_django",
            "docker pull a26796879/just_learn_celery",
            "docker-compose up -d"
         ],
         "image": "appleboy/drone-ssh",
         "name": "deploy-services",
         "settings": {
            "host": {
               "from_secret": "service_host"
            },
            "key": {
               "from_secret": "id_rsa"
            }
         },
         "when": {
            "event": {
               "exclude": [
                  "push"
               ]
            }
         }
      }
   ]
}
---
{
   "kind": "pipeline",
   "name": "publish_to_workers_celery1_host",
   "steps": [
      {
         "commands": [
            "ls",
            "cd just_learn_Django",
            "docker-compose stop",
            "sudo git reset --hard",
            "sudo git pull",
            "sudo docker-compose build",
            "docker pull a26796879/just_learn_django",
            "docker pull a26796879/just_learn_celery",
            "docker-compose up -d"
         ],
         "image": "appleboy/drone-ssh",
         "name": "deploy-workers_celery1_host",
         "settings": {
            "host": {
               "from_secret": "celery1_host"
            },
            "key": {
               "from_secret": "id_rsa"
            }
         },
         "when": {
            "event": {
               "exclude": [
                  "push"
               ]
            }
         }
      }
   ]
}
---
{
   "kind": "pipeline",
   "name": "publish_to_workers_celery2_host",
   "steps": [
      {
         "commands": [
            "ls",
            "cd just_learn_Django",
            "docker-compose stop",
            "sudo git reset --hard",
            "sudo git pull",
            "sudo docker-compose build",
            "docker pull a26796879/just_learn_django",
            "docker pull a26796879/just_learn_celery",
            "docker-compose up -d"
         ],
         "image": "appleboy/drone-ssh",
         "name": "deploy-workers_celery2_host",
         "settings": {
            "host": {
               "from_secret": "celery2_host"
            },
            "key": {
               "from_secret": "id_rsa"
            }
         },
         "when": {
            "event": {
               "exclude": [
                  "push"
               ]
            }
         }
      }
   ]
}
---
{
   "kind": "pipeline",
   "name": "publish_to_workers_celery3_host",
   "steps": [
      {
         "commands": [
            "ls",
            "cd just_learn_Django",
            "docker-compose stop",
            "sudo git reset --hard",
            "sudo git pull",
            "sudo docker-compose build",
            "docker pull a26796879/just_learn_django",
            "docker pull a26796879/just_learn_celery",
            "docker-compose up -d"
         ],
         "image": "appleboy/drone-ssh",
         "name": "deploy-workers_celery3_host",
         "settings": {
            "host": {
               "from_secret": "celery3_host"
            },
            "key": {
               "from_secret": "id_rsa"
            }
         },
         "when": {
            "event": {
               "exclude": [
                  "push"
               ]
            }
         }
      }
   ]
}
