version: "3.7"

services:
    django:
        build: .
        container_name: django
        command: >
            bash -c "python3 manage.py migrate
            && python3 manage.py runserver 0.0.0.0:8000"
        volumes:
            - .:/usr/src/app/
        ports:
            - "80:8000"
        environment:
            - DEBUG=1
            - CELERY_BROKER=amqp://niceguy:niceguy@35.227.175.4:5672
            - CELERY_BACKEND=redis://redis:6379/0
        depends_on:
            - pgdb
            - redis
    celery:
        build: .
        command: 'celery -A just_learn flower -l INFO'
        volumes:
            - .:/usr/src/app
        ports:
            - "5555:5555"
        environment:
            - DEBUG=1
            - CELERY_BROKER=amqp://niceguy:niceguy@35.227.175.4:5672
            - CELERY_BACKEND=redis://redis:6379/0
        depends_on:
            - django
            - redis
    pgdb:
        image: postgres
        container_name: pgdb
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        volumes:
            - pgdata:/var/lib/postgresql/data/
        ports:
            - "5432:5432"
    redis:
        image: "redis:alpine"
        
volumes:
    pgdata:

