# Generated by Django 3.2.13 on 2022-04-23 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='news_crawler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('publisher', models.CharField(max_length=50)),
                ('url', models.URLField()),
                ('date', models.DateTimeField()),
                ('keyword', models.CharField(max_length=50)),
            ],
        ),
    ]
